version: '3'

services:
  webserver:
    build:
      context: './docker/bin/${PHP_VERSION}'
    container_name: '${APP_NAME}-${PHP_VERSION}'
    restart: 'always'
    ports:
      - '${HOST_PORT}:80'
    links:
      - 'database'
    volumes:
      - '.:/var/www/html'
      - '${PHP_INI}:/usr/local/etc/php/php.ini'
      - '${APACHE_LOG_DIR}:/var/log/apache2'
    environment:
      APACHE_DOCUMENT_ROOT: '${APACHE_DOCUMENT_ROOT}'
      PMA_PORT: '${PHPMYADMIN_PORT}'
      MYSQL_ROOT_PASSWORD: '${DATABASE_PASSWORD}'

  database:
    build:
      context: './docker/bin/${DATABASE_VERSION}'
    container_name: '${APP_NAME}-${DATABASE_VERSION}'
    restart: 'always'
    ports:
      - '127.0.0.1:${DATABASE_PORT}:3306'
    volumes:
      - '${DATABASE_INITDB_DIR}:/docker-entrypoint-initdb.d'
      - '${DATABASE_DATA_DIR}:/var/lib/mysql'
      - '${DATABASE_LOG_DIR}:/var/log/mysql'
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    container_name: '${APP_NAME}-phpmyadmin'
    links:
      - 'database'
    environment:
      PMA_HOST: 'database'
      PMA_PORT: 3306
      PMA_USER: '${DATABASE_USER}'
      PMA_PASSWORD: '${DATABASE_PASSWORD}'
      MYSQL_USER: '${DATABASE_USER}'
      MYSQL_PASSWORD: '${DATABASE_PASSWORD}'
      UPLOAD_LIMIT: '${PHPMYADMIN_UPLOAD_LIMIT}'
      MEMORY_LIMIT: '${PHPMYADMIN_MEMORY_LIMIT}'
    ports:
      - '${PHPMYADMIN_PORT}:80'
    volumes:
      - /sessions
      - ${PHP_INI}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
