version: '2'
services:
  website:
    image: nginx
    restart: always
    networks:
      - web
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html
    labels:
      - 'traefik.enable=true'
      - 'traefik.frontend.rule=Host:${APP_URL}'
      - 'traefik.docker.network=web'

networks:
  web:
    external: true
